# Rocky Linux 9 / RHEL 9 / Alma 9 minimal kickstart — generated by ClusterOne
# Per-host variables substituted at render time. See
# core/services/autoinstall_renderer.py for the full variable list.
${disk_premount}
# --- Install source: assume installer mounted via Virtual Media ---
cdrom

# --- Localization ---
keyboard --vckeymap=us --xlayouts='us'
lang en_US.UTF-8
timezone UTC --utc

# --- Network: DHCP on first interface; hostname per ClusterOne profile ---
network --bootproto=dhcp --device=link --activate --hostname=${hostname}

# --- Disk: WIPE the disk ClusterOne resolved for this host. Targeted by
# SERIAL via a %pre resolver (stable across BMC-vs-host enumeration); a literal
# device name is used only when the BMC reported no serial. ClusterOne refuses
# to render at all if it cannot identify the disk safely.
${disk_directives}
autopart --type=lvm --noswap

# --- Auth ---
rootpw --plaintext ${root_password}
selinux --enforcing
firewall --enabled --ssh
firstboot --disable
services --enabled=sshd,chronyd

# --- Minimal package set: get to SSH-reachable, then Ansible/etc. takes over ---
%packages --inst-langs=en
@^minimal-environment
chrony
openssh-server
sudo
vim-minimal
%end

# --- Post-install: drop authorized_keys for root, signal ClusterOne ---
%post --erroronfail
mkdir -p /root/.ssh
chmod 700 /root/.ssh
cat > /root/.ssh/authorized_keys <<'EOF'
${ssh_authorized_keys}
EOF
chmod 600 /root/.ssh/authorized_keys
%end

reboot
